;;;; library.lisp -- predicates defined in qprolog syntax (compiled like user code).
(in-package :qp)

(let ((*loading-library* t))
  (dolist (form
           '((<- (\\+ ?g) (call ?g) ! fail)
             (<- (\\+ _))
             (<- (getenv_or ?name ?default ?value)
                 (:or (getenv ?name ?v0) -> (unify ?value ?v0) (unify ?value ?default)))
             (<- (once ?g) (call ?g) !)
             (<- (ignore ?g) (call ?g) !)
             (<- (ignore _))
             (<- (forall ?c ?a) (\\+ (:and ?c (\\+ ?a))))
             (<- (append nil ?l ?l))
             (<- (append (?h . ?t) ?l (?h . ?r)) (append ?t ?l ?r))
             (<- (member ?x (?x . _)))
             (<- (member ?x (_ . ?t)) (member ?x ?t))
             (<- (memberchk ?x ?l) (member ?x ?l) !)
             (<- (reverse ?l ?r) (reverse ?l nil ?r))
             (<- (reverse nil ?a ?a))
             (<- (reverse (?h . ?t) ?a ?r) (reverse ?t (?h . ?a) ?r))
             (<- (select ?x (?x . ?t) ?t))
             (<- (select ?x (?h . ?t) (?h . ?r)) (select ?x ?t ?r))
             (<- (nth0 ?i ?l ?e) (nth ?l 0 ?i ?e))
             (<- (nth1 ?i ?l ?e) (nth ?l 1 ?i ?e))
             (<- (nth (?h . ?t) ?b ?i ?e)
              (:or (integer ?i) -> (:and (is ?k (- ?i ?b)) (>= ?k 0) (nth_fixed ?k (?h . ?t) ?e))
                   (nth_gen (?h . ?t) ?b ?i ?e)))
             (<- (nth_fixed 0 (?e . _) ?e))
             (<- (nth_fixed ?k (_ . ?t) ?e) (> ?k 0) (is ?k1 (- ?k 1)) (nth_fixed ?k1 ?t ?e))
             (<- (nth_gen (?e . _) ?b ?b ?e))
             (<- (nth_gen (_ . ?t) ?b ?i ?e) (is ?b1 (+ ?b 1)) (nth_gen ?t ?b1 ?i ?e))
             (<- (last (?x) ?x))
             (<- (last (_ . ?t) ?x) (last ?t ?x))
             (<- (sum_list ?l ?s) (sum_list ?l 0 ?s))
             (<- (sum_list nil ?s ?s))
             (<- (sum_list (?h . ?t) ?a ?s) (is ?a1 (+ ?a ?h)) (sum_list ?t ?a1 ?s))
             (<- (max_list (?h . ?t) ?m) (max_list ?t ?h ?m))
             (<- (max_list nil ?m ?m))
             (<- (max_list (?h . ?t) ?a ?m) (is ?a1 (max ?a ?h)) (max_list ?t ?a1 ?m))
             (<- (min_list (?h . ?t) ?m) (min_list ?t ?h ?m))
             (<- (min_list nil ?m ?m))
             (<- (min_list (?h . ?t) ?a ?m) (is ?a1 (min ?a ?h)) (min_list ?t ?a1 ?m))
             (<- (delete nil _ nil))
             (<- (delete (?h . ?t) ?x ?r)
              (:or (\\+ (unify ?h ?x)) -> (:and (unify ?r (?h . ?r1)) (delete ?t ?x ?r1))
                   (delete ?t ?x ?r)))
             (<- (exclude _ nil nil))
             (<- (exclude ?p (?h . ?t) ?r)
              (:or (call ?p ?h) -> (exclude ?p ?t ?r) (:and (unify ?r (?h . ?r1)) (exclude ?p ?t ?r1))))
             (<- (include _ nil nil))
             (<- (include ?p (?h . ?t) ?r)
              (:or (call ?p ?h) -> (:and (unify ?r (?h . ?r1)) (include ?p ?t ?r1)) (include ?p ?t ?r)))
             (<- (maplist _ nil))
             (<- (maplist ?p (?a . ?as)) (call ?p ?a) (maplist ?p ?as))
             (<- (maplist _ nil nil))
             (<- (maplist ?p (?a . ?as) (?b . ?bs)) (call ?p ?a ?b) (maplist ?p ?as ?bs))
             (<- (maplist _ nil nil nil))
             (<- (maplist ?p (?a . ?as) (?b . ?bs) (?c . ?cs)) (call ?p ?a ?b ?c) (maplist ?p ?as ?bs ?cs))
             (<- (foldl ?g ?l ?v0 ?v) (foldl_ ?l ?g ?v0 ?v))
             (<- (foldl_ nil _ ?v ?v))
             (<- (foldl_ (?x . ?xs) ?g ?v0 ?v) (call ?g ?x ?v0 ?v1) (foldl_ ?xs ?g ?v1 ?v))
             (<- (sumlist ?l ?s) (sum_list ?l ?s))
             (<- (list_to_set ?l ?s) (lts ?l nil ?s))
             (<- (lts nil _ nil))
             (<- (lts (?h . ?t) ?seen ?r)
              (:or (memberchk_eq ?h ?seen) -> (lts ?t ?seen ?r)
                   (:and (unify ?r (?h . ?r1)) (lts ?t (?h . ?seen) ?r1))))
             (<- (memberchk_eq ?x (?y . ?t)) (:or (== ?x ?y) -> true (memberchk_eq ?x ?t)))
             (<- (setof ?t ?g ?s) (findall ?t ?g ?l) (\\== ?l nil) (sort ?l ?s))
             (<- (bagof ?t ?g ?l) (findall ?t ?g ?l) (\\== ?l nil))
             (<- (findall ?t ?g ?l ?tail) (findall ?t ?g ?l0) (append ?l0 ?tail ?l))
             (<- (aggregate_all count ?g ?c) (findall x ?g ?l) (length ?l ?c))
             (<- (aggregate_all (count) ?g ?c) (findall x ?g ?l) (length ?l ?c))
             (<- (aggregate_all (sum ?e) ?g ?s) (findall ?e ?g ?l) (sum_list ?l ?s))
             (<- (aggregate_all (max ?e) ?g ?m) (findall ?e ?g ?l) (\\== ?l nil) (max_list ?l ?m))
             (<- (aggregate_all (min ?e) ?g ?m) (findall ?e ?g ?l) (\\== ?l nil) (min_list ?l ?m))
             (<- (repeat))
             (<- (repeat) (repeat))
             (<- (apply ?g ?args) (=.. ?g (?f . ?a0)) (append ?a0 ?args ?a1) (=.. ?g2 (?f . ?a1)) (call ?g2))))
    (eval form)))
