;;;; Validate a numeric Parametric UMAP corpus without external libraries.

(defvar *validate-parametric-corpus-run-main* t)

(defun corpus-read-form (path)
  (with-open-file (stream path)
    (let ((*read-eval* nil)) (read stream))))

(defun corpus-finite-real-p (value)
  (and (realp value) (= value value)
       (< (abs (coerce value 'double-float))
          most-positive-double-float)))

(defun validate-parametric-corpus (path)
  (let* ((corpus (corpus-read-form path))
         (records (getf corpus :records))
         (preprocessing (getf corpus :preprocessing))
         (means (getf preprocessing :means))
         (scales (getf preprocessing :scales))
         (dimension (length means)))
    (unless (and (eq (getf corpus :format) :parametric-umap-corpus)
                 (= (getf corpus :version) 1))
      (error "Unsupported Parametric UMAP corpus format."))
    (unless (and records (plusp dimension) (= dimension (length scales)))
      (error "Corpus needs records and matching preprocessing vectors."))
    (unless (every (lambda (scale) (and (corpus-finite-real-p scale)
                                        (plusp scale))) scales)
      (error "Every preprocessing scale must be finite and positive."))
    (let ((ids '()) (group-splits (make-hash-table :test #'equal)))
      (dolist (record records)
        (let ((id (getf record :id)) (group (getf record :group))
              (split (getf record :split)) (input (getf record :input))
              (target (getf record :target)))
          (unless (and id group (member split '(:train :validation)))
            (error "Invalid record identity or split: ~S." record))
          (when (member id ids :test #'equal) (error "Duplicate record ID ~S." id))
          (push id ids)
          (let ((known (gethash group group-splits)))
            (when (and known (not (eq known split)))
              (error "Group ~S crosses train and validation splits." group))
            (setf (gethash group group-splits) split))
          (unless (and (= (length input) dimension)
                       (= (length target) 2)
                       (every #'corpus-finite-real-p input)
                       (every #'corpus-finite-real-p target))
            (error "Invalid numeric input or target for ~S." id))))
      (unless (find :train records :key (lambda (record) (getf record :split)))
        (error "Corpus has no training records."))
      (format t "Validated ~D records, ~D features, ~D groups.~%"
              (length records) dimension (hash-table-count group-splits)))
    corpus))

(when *validate-parametric-corpus-run-main*
  (let ((arguments (cdr sb-ext:*posix-argv*)))
    (unless (= (length arguments) 1)
      (error "Usage: sbcl --script smc-trainer/validate-corpus.lisp CORPUS.sexp"))
    (validate-parametric-corpus (first arguments))))
