;;;; Common Lisp regression checks for complete source preservation and sliders.
(defparameter *sarcoma-page-run-main* nil)
(load (merge-pathnames "../sarcoma-specific/build-preferences-page.lisp" *load-truename*))
(defparameter *smc-search-run-main* nil)
(load (merge-pathnames "smc/search-umap.lisp" *sarcoma-root*))
(let* ((corpus (merge-pathnames "smc-trainer/corpus/sarcoma-awrs-shards/manifest.sexp" *sarcoma-root*))
       (weights (merge-pathnames "smc-trainer/cl-sarcoma-awrs-model.sexp" *sarcoma-root*))
       (data (sarcoma-page-data corpus weights))
       (atlas (getf data :atlas)) (features (getf data :features))
       (problem (getf data :problem))
       (spec (getf problem :data))
       (source (read-dataset (merge-pathnames (getf spec :file) *sarcoma-root*) spec))
       (checks 0) (curves 0))
  (dolist (point atlas)
    (let* ((row (getf point :evidence))
           (original (find (getf point :id) source :key (lambda (p) (getf p :id)) :test #'equal)))
      (assert (equalp row original))
      (assert (>= (length (getf row :curve)) 2))
      (incf curves)
      (loop for raw in (getf point :raw-values)
            for expected in (getf point :input)
            for feature in features
            for actual = (/ (- (smc-transform-value (getf feature :transformation) raw)
                               (getf feature :mean)) (getf feature :scale))
            do (assert (< (abs (- expected actual)) 1.0d-10)) (incf checks))))
  (let* ((artifact (predict-read-form weights))
         (model (form-parametric-model (getf artifact :model))))
    (with-open-file (s "/tmp/sarcoma-prediction-check.json" :direction :output :if-exists :supersede)
      (write-json-pretty (loop for p in atlas collect
         (list :input (getf p :input) :prediction (parametric-predict model (getf p :input)))) s)))
  (format t "PASS: ~D full evidence records/curves preserved; ~D exact slider conversions.~%" curves checks))
