;;;; builtins.lisp -- builtin predicates written in Lisp.
(in-package :qp)
(engine-policy)

(defvar *cons-name* (intern "[|]" :qp))

;;; ------------------------------------------------------------------ control and comparison
(defdet true () t)
(defdet false () nil)
(defdet fail () nil)
(defdet ! () t)
(defdet unify (a b) (unify a b))
(defdet is (x e) (unify-num x (ar-eval e)))
(defdet < (a b) (ar< (ar-val a) (ar-val b)))
(defdet > (a b) (ar> (ar-val a) (ar-val b)))
(defdet <= (a b) (ar<= (ar-val a) (ar-val b)))
(defdet >= (a b) (ar>= (ar-val a) (ar-val b)))
(defdet = (a b) (ar= (ar-val a) (ar-val b)))
(defdet /= (a b) (ar/= (ar-val a) (ar-val b)))
(defdet == (a b) (term== a b))
(defdet \\== (a b) (not (term== a b)))
(defdet @< (a b) (< (compare-terms a b) 0))
(defdet @> (a b) (> (compare-terms a b) 0))
(defdet @=< (a b) (<= (compare-terms a b) 0))
(defdet @>= (a b) (>= (compare-terms a b) 0))
(defdet var (x) (pv-p (deref x)))
(defdet nonvar (x) (not (pv-p (deref x))))
(defdet atom (x) (let ((x (deref x))) (and (symbolp x) t)))
(defdet number (x) (numberp (deref x)))
(defdet integer (x) (integerp (deref x)))
(defdet float (x) (floatp (deref x)))
(defdet atomic (x) (let ((x (deref x))) (not (or (pv-p x) (consp x) (simple-vector-p x)))))
(defdet compound (x) (let ((x (deref x))) (or (consp x) (simple-vector-p x))))
(defdet callable (x) (let ((x (deref x))) (or (and (symbolp x) x) (simple-vector-p x))))
(defdet is_list (x) (listp-term x))
(defdet ground (x) (ground-term-p x))
(defdet halt () (finish-output) (sb-ext:exit :code 0 :abort t))

(defun unifiable-p (a b)
  (let ((mark $tr) (hb $hb))
    (setf $hb $vc)
    (prog1 (unify a b) (undo-trail mark) (setf $hb hb))))
(defdet \\= (a b) (not (unifiable-p a b)))

;;; ------------------------------------------------------------------ term construction / inspection
(defun term-arg (n tm)
  (cond ((simple-vector-p tm) (if (and (integerp n) (<= 1 n (1- (length tm)))) (svref tm n) '%none))
        ((consp tm) (case n (1 (car tm)) (2 (cdr tm)) (t '%none)))
        (t '%none)))

(defdet %arg (n tm a)
  (let ((x (term-arg (deref n) (deref tm))))
    (and (not (eq x '%none)) (unify a x))))

(deflisp arg 3
  (let ((n (deref (svref $a 0))) (tm (deref (svref $a 1))) (a (svref $a 2)))
    (cond ((integerp n)
           (let ((x (term-arg n tm)))
             (if (and (not (eq x '%none)) (unify a x)) $cp (backtrack))))
          ((pv-p n)
           (let ((size (cond ((simple-vector-p tm) (1- (length tm))) ((consp tm) 2) (t 0))) (i 1))
             (if (zerop size)
                 (backtrack)
                 (call-iter (lambda ()
                              (loop
                                (when (> i size) (return :fail))
                                (let ((k i))
                                  (incf i)
                                  (let ((mark $tr))
                                    (if (and (unify n k) (unify a (term-arg k tm)))
                                        (return (if (> i size) :last t))
                                        (undo-trail mark))))))))))
          (t (type-err 'integer n)))))

(defdet functor (term name arity)
  (let ((tm (deref term)))
    (cond ((pv-p tm)
           (let ((n (deref name)) (a (deref arity)))
             (when (or (pv-p n) (pv-p a)) (inst-err))
             (unless (integerp a) (type-err 'integer a))
             (cond ((eql a 0) (unify tm n))
                   ((and (eq n *cons-name*) (eql a 2)) (unify tm (cons (new-var) (new-var))))
                   (t (unless (and (symbolp n) n) (type-err 'atom n))
                      (let ((v (make-array (1+ a))))
                        (setf (svref v 0) n)
                        (loop for i from 1 to a do (setf (svref v i) (new-var)))
                        (unify tm v))))))
          ((consp tm) (and (unify name *cons-name*) (unify arity 2)))
          ((simple-vector-p tm) (and (unify name (svref tm 0)) (unify arity (1- (length tm)))))
          (t (and (unify name tm) (unify arity 0))))))

(defdet =.. (term list)
  (let ((tm (deref term)))
    (cond ((pv-p tm)
           (let ((l (term-list list)))
             (when (member l '(:partial :improper)) (inst-err))
             (let ((n (deref (car l))) (args (cdr l)))
               (cond ((null args) (unify tm n))
                     ((and (eq n *cons-name*) (= (length args) 2)) (unify tm (cons (first args) (second args))))
                     (t (unless (and (symbolp n) n) (type-err 'atom n))
                        (unify tm (coerce (cons n args) 'simple-vector)))))))
          ((consp tm) (unify list (list *cons-name* (car tm) (cdr tm))))
          ((simple-vector-p tm) (unify list (coerce tm 'list)))
          (t (unify list (list tm))))))

(defdet copy_term (a b) (unify b (copy-term a)))
(defdet term_variables (tm l) (unify l (list->term (term-vars tm))))

(defdet compare (o a b)
  (unify o (let ((c (compare-terms a b))) (cond ((< c 0) '<) ((> c 0) '>) (t '=)))))

;;; ------------------------------------------------------------------ sorting
(defun proper-term-list (l)
  (let ((r (term-list l)))
    (case r (:partial (inst-err)) (:improper (type-err 'list l)) (t r))))

(defun dedup-sorted (l)
  (let ((out nil))
    (dolist (x l) (unless (and out (eql 0 (compare-terms (car out) x))) (push x out)))
    (nreverse out)))

(defun term< (a b) (< (the fixnum (compare-terms a b)) 0))

(defdet msort (l s) (unify s (list->term (stable-sort (copy-list (proper-term-list l)) #'term<))))
(defdet sort (l s) (unify s (list->term (dedup-sorted (stable-sort (copy-list (proper-term-list l)) #'term<)))))
(defdet keysort (l s)
  (let ((items (proper-term-list l)))
    (dolist (x items)
      (let ((x (deref x)))
        (unless (and (simple-vector-p x) (= (length x) 3) (string= (symbol-name (svref x 0)) "-"))
          (if (pv-p x) (inst-err) (type-err 'pair x)))))
    (unify s (list->term (stable-sort (copy-list items) (lambda (a b) (term< (svref (deref a) 1) (svref (deref b) 1))))))))
(defdet predsort_default (l s) (unify l s))

;;; ------------------------------------------------------------------ lists
(defdet numlist (lo hi l)
  (let ((lo (deref lo)) (hi (deref hi)))
    (unless (integerp lo) (type-err 'integer lo))
    (unless (integerp hi) (type-err 'integer hi))
    (unify l (let ((r nil)) (loop for i from hi downto lo do (push i r)) r))))

(defun fresh-list (n) (let ((r nil)) (dotimes (i n r) (push (new-var) r))))

(deflisp length 2
  (let ((l (deref (svref $a 0))) (n (deref (svref $a 1))) (len 0))
    (declare (fixnum len))
    (loop while (consp l) do (incf len) (setq l (deref (cdr l))))
    (cond ((null l) (if (unify n len) $cp (backtrack)))
          ((pv-p l)
           (cond ((integerp n)
                  (if (and (>= n len) (unify l (fresh-list (- n len)))) $cp (backtrack)))
                 ((pv-p n)
                  (let ((k 0) (tail l) (len0 len))
                    (call-iter (lambda ()
                                 (prog1 (and (unify tail (fresh-list k)) (unify n (+ len0 k)))
                                   (incf k))))))
                 (t (type-err 'integer n))))
          (t (backtrack)))))

(deflisp between 3
  (let ((lo (deref (svref $a 0))) (hi (deref (svref $a 1))) (x (deref (svref $a 2))))
    (when (pv-p lo) (inst-err))
    (when (pv-p hi) (inst-err))
    (let ((hi (if (symbolp hi) most-positive-fixnum hi)))
      (cond ((integerp x) (if (<= lo x hi) $cp (backtrack)))
            ((pv-p x)
             (if (> lo hi)
                 (backtrack)
                 (let ((i lo))
                   (declare (fixnum i))
                   (call-iter (lambda ()
                                (let ((k i))
                                  (incf i)
                                  (bind x k)
                                  (if (>= k hi) :last t)))))))
            (t (type-err 'integer x))))))

(defdet succ (a b)
  (let ((a (deref a)) (b (deref b)))
    (cond ((integerp a) (unify b (1+ a)))
          ((and (integerp b) (> b 0)) (unify a (1- b)))
          (t nil))))
(defdet plus (a b c)
  (let ((a (deref a)) (b (deref b)) (c (deref c)))
    (cond ((and (integerp a) (integerp b)) (unify c (+ a b)))
          ((and (integerp a) (integerp c)) (unify b (- c a)))
          ((and (integerp b) (integerp c)) (unify a (- c b)))
          (t (inst-err)))))

;;; ------------------------------------------------------------------ atoms and text
(defun text-of (x)
  (let ((x (deref x)))
    (cond ((pv-p x) (inst-err))
          ((null x) "[]")
          ((symbolp x) (symbol-name x))
          ((stringp x) x)
          ((numberp x) (number-text x))
          (t (type-err 'atomic x)))))

(defun number-text (x)
  (if (floatp x)
      (let ((*read-default-float-format* 'double-float)) (format nil "~F" x))
      (format nil "~D" x)))

(defun text->atom (s) (intern s :qp))

(defun text->number (s)
  (let ((v (ignore-errors
            (let ((*read-eval* nil) (*read-default-float-format* 'double-float) (*package* (find-package :qp)))
              (and (plusp (length s))
                   (or (digit-char-p (char s 0)) (and (> (length s) 1) (find (char s 0) "+-")))
                   (multiple-value-bind (v pos) (read-from-string s)
                     (and (numberp v) (= pos (length s)) v)))))))
    v))

(defun codes-of (s) (map 'list #'char-code s))
(defun chars-of (s) (map 'list (lambda (c) (text->atom (string c))) s))
(defun text-from-codes (l) (map 'string (lambda (c) (code-char (deref c))) (proper-term-list l)))
(defun text-from-chars (l) (apply #'concatenate 'string (mapcar (lambda (c) (text-of c)) (proper-term-list l))))

(defdet atom_codes (a l)
  (let ((x (deref a)))
    (if (pv-p x)
        (unify x (text->atom (text-from-codes l)))
        (unify l (codes-of (text-of x))))))
(defdet atom_chars (a l)
  (let ((x (deref a)))
    (if (pv-p x)
        (unify x (text->atom (text-from-chars l)))
        (unify l (chars-of (text-of x))))))
(defdet number_codes (n l)
  (let ((x (deref n)))
    (if (pv-p x)
        (let ((v (text->number (text-from-codes l)))) (and v (unify x v)))
        (unify l (codes-of (text-of x))))))
(defdet atom_number (a n)
  (let ((x (deref a)))
    (if (pv-p x)
        (let ((v (deref n))) (if (numberp v) (unify x (text->atom (number-text v))) (inst-err)))
        (let ((v (text->number (text-of x)))) (and v (unify n v))))))
(defdet atom_length (a n) (unify n (length (text-of a))))
(defdet char_code (c n)
  (let ((x (deref c)))
    (if (pv-p x) (unify x (text->atom (string (code-char (deref n))))) (unify n (char-code (char (text-of x) 0))))))
(defdet upcase_atom (a b) (unify b (text->atom (string-upcase (text-of a)))))
(defdet atom_concat (a b c)
  (let ((x (deref a)) (y (deref b)))
    (if (and (not (pv-p x)) (not (pv-p y)))
        (unify c (text->atom (concatenate 'string (text-of x) (text-of y))))
        (let ((z (text-of c)))
          (cond ((not (pv-p x)) (let ((p (text-of x))) (and (>= (length z) (length p)) (string= p z :end2 (length p))
                                                          (unify y (text->atom (subseq z (length p)))))))
                ((not (pv-p y)) (let ((s (text-of y))) (and (>= (length z) (length s))
                                                          (string= s z :start2 (- (length z) (length s)))
                                                          (unify x (text->atom (subseq z 0 (- (length z) (length s))))))))
                (t (inst-err)))))))

;;; ------------------------------------------------------------------ output
(defvar *qp-out* nil "Output stream of write/nl/format; NIL means *STANDARD-OUTPUT*.")
(defmacro out () '(or *qp-out* *standard-output*))

(defun write-atom-text (a stream)
  (write-string (if (null a) "[]" (symbol-name a)) stream))

(defun write-term-to (term stream &optional (names (make-hash-table :test 'eq)))
  (let ((x (deref term)))
    (cond ((pv-p x) (format stream "_G~D" (or (gethash x names) (setf (gethash x names) (hash-table-count names)))))
          ((null x) (write-string "[]" stream))
          ((symbolp x) (write-atom-text x stream))
          ((consp x)
           (write-char #\[ stream)
           (loop (write-term-to (car x) stream names)
                 (setq x (deref (cdr x)))
                 (cond ((consp x) (write-char #\, stream))
                       ((null x) (return))
                       (t (write-char #\| stream) (write-term-to x stream names) (return))))
           (write-char #\] stream))
          ((simple-vector-p x)
           (write-atom-text (svref x 0) stream)
           (write-char #\( stream)
           (loop for i from 1 below (length x)
                 do (when (> i 1) (write-char #\, stream))
                    (write-term-to (svref x i) stream names))
           (write-char #\) stream))
          ((floatp x) (write-string (number-text x) stream))
          (t (format stream "~A" x)))))

(defdet write (x) (write-term-to x (out)) t)
(defdet print (x) (write-term-to x (out)) t)
(defdet writeln (x) (write-term-to x (out)) (terpri (out)) t)
(defdet write_canonical (x) (write-term-to x (out)) t)
(defdet nl () (terpri (out)) t)
(defdet tab (n) (dotimes (i (ar-eval n)) (write-char #\Space (out))) t)
(defdet put_char (c) (write-string (text-of c) (out)) t)

(defun qp-format (fmt args)
  (let ((f (text-of fmt))
        (args (let ((a (deref args))) (if (or (null a) (consp a)) (proper-term-list a) (list a)))))
    (let ((i 0) (n (length f)))
      (loop while (< i n)
            do (let ((c (char f i)))
                 (incf i)
                 (if (and (char= c #\~) (< i n))
                     (let ((d (char f i)))
                       (incf i)
                       (case d
                         (#\n (terpri (out)))
                         (#\~ (write-char #\~ (out)))
                         ((#\w #\p #\q) (write-term-to (pop args) (out)))
                         (#\a (write-string (text-of (pop args)) (out)))
                         (#\d (format (out) "~D" (ar-eval (pop args))))
                         (t (error "format: unsupported directive ~~~A" d))))
                     (write-char c (out))))))
    t))
(defdet format (f) (qp-format f nil))
(defdet format (f a) (qp-format f a))

(defvar *last-runtime* 0)
(defdet statistics (key val)
  (let* ((k (symbol-name (deref key)))
         (ms (floor (* 1000 (get-internal-run-time)) internal-time-units-per-second)))
    (cond ((or (string-equal k "runtime") (string-equal k "cputime") (string-equal k "process_cputime"))
           (if (string-equal k "runtime")
               (prog1 (unify val (list ms (- ms *last-runtime*))) (setf *last-runtime* ms))
               (unify val (/ ms 1000d0))))
          ((string-equal k "walltime")
           (let ((w (floor (* 1000 (get-internal-real-time)) internal-time-units-per-second)))
             (unify val (list w 0))))
          ((string-equal k "inferences") (unify val 0))
          (t (unify val 0)))))

;;; ------------------------------------------------------------------ database
(defdet assertz (c) (assert-term c :end) t)
(defdet assert (c) (assert-term c :end) t)
(defdet asserta (c) (assert-term c :start) t)

(defun head-pred (h &optional create)
  (multiple-value-bind (name args) (goal-parts (deref h))
    (let ((n (length args)))
      (if create (get-pred name n) (find-pred name n)))))

(defun body-term-of (c frame)
  (let ((goals (mapcar (lambda (g) (instantiate g frame)) (clause-body c))))
    (cond ((null goals) 'true)
          ((null (cdr goals)) (car goals))
          (t (coerce (cons :and goals) 'simple-vector)))))

(defun unify-clause (c h-args b frame)
  "Unify the head arguments (list of runtime terms) and body term of clause C."
  (let ((i 0) (args (clause-head-args c)))
    (declare (fixnum i))
    (dolist (tpl args)
      (unless (unify-tpl tpl (nth i h-args) frame) (return-from unify-clause nil))
      (incf i))
    (or (null b) (unify b (body-term-of c frame)))))

(defun clause-source (p h)
  "Closure returning the next matching visible clause of P for head H (or NIL)."
  (let* ((gen $gen) (a0 (and (> (pred-arity p) 0) (nth-arg h 1)))
         (key (if a0 (call-key a0) :any)))
    (multiple-value-bind (start idxp) (scan-start p key)
      (let ((cur (next-match start gen key idxp)))
        (lambda ()
          (let ((c cur))
            (when c
              (setq cur (next-match (if idxp (clause-inext c) (clause-next c)) gen key idxp)))
            c))))))

(defun nth-arg (h i) (svref (deref h) i))
(defun head-args-of (h) (let ((h (deref h))) (if (simple-vector-p h) (cdr (coerce h 'list)) nil)))

(defun clause-iter (head body erase)
  (let* ((p (head-pred head)))
    (if (or (null p) (not (pred-dynamic p)))
        nil
        (let ((next (clause-source p (deref head))) (h-args (head-args-of head)))
          (lambda ()
            (let ((mark $tr))
              (loop
                (let ((c (funcall next)))
                  (unless c (return :fail))
                  (let ((frame (make-array (clause-nvars c) :initial-element '%unset)))
                    (if (unify-clause c h-args body frame)
                        (progn (when erase (erase-clause c)) (return t))
                        (undo-trail mark)))))))))))

(deflisp retract 1
  (multiple-value-bind (h b) (split-clause-term (svref $a 0))
    (when (pv-p h) (inst-err))
    (let ((it (clause-iter h (if (eq b 'true) nil b) t)))
      (if it (call-iter it) (backtrack)))))

(deflisp clause 2
  (let* ((h (deref (svref $a 0))) (b (svref $a 1)))
    (when (pv-p h) (inst-err))
    (let ((it (clause-iter h b nil)))
      (if it (call-iter it) (backtrack)))))

(defdet retractall (h)
  (let ((p (head-pred h t)))
    (unless (pred-dynamic p) (make-dynamic p))
    (let ((next (clause-source p (deref h))) (h-args (head-args-of h)))
      (loop
        (let ((c (funcall next)))
          (unless c (return t))
          (let ((mark $tr) (hb $hb) (ok nil))
            (setf $hb $vc)
            (setq ok (unify-clause c h-args nil (make-array (clause-nvars c) :initial-element '%unset)))
            (undo-trail mark)
            (setf $hb hb)
            (when ok (erase-clause c))))))))

(defun spec-list (spec)
  (let ((s (deref spec)))
    (cond ((and (simple-vector-p s) (string= (symbol-name (svref s 0)) ",")) (append (spec-list (svref s 1)) (spec-list (svref s 2))))
          ((consp s) (mapcan #'spec-list (proper-term-list s)))
          (t (list s)))))

(defdet dynamic (spec)
  (dolist (s (spec-list spec) t)
    (let ((s (deref s)))
      (make-dynamic (get-pred (deref (svref s 1)) (deref (svref s 2)))))))

(defdet abolish (spec)
  (let* ((s (deref spec)) (p (find-pred (deref (svref s 1)) (deref (svref s 2)))))
    (when p (wipe-pred p))
    t))

;;; ------------------------------------------------------------------ all-solutions
(defdet findall (template goal result)
  (let ((acc nil))
    (solve-iter goal (lambda () (push (copy-term template) acc) nil))
    (unify result (list->term (nreverse acc)))))
