;;;; Sarcoma page: preserve complete evidence records and train-time transforms.
(defparameter *sarcoma-directory* (make-pathname :name nil :type nil :defaults *load-truename*))
(defparameter *sarcoma-root* (merge-pathnames "../" *sarcoma-directory*))
(defparameter *build-umap-run-main* nil)
(load (merge-pathnames "build-umap.lisp" *sarcoma-root*))
(defparameter *parametric-predict-run-main* nil)
(load (merge-pathnames "smc-trainer/predict.lisp" *sarcoma-root*))
(load (merge-pathnames "smc-trainer/shards.lisp" *sarcoma-root*))
(defun preferences-model-json-plist (model)
  "Export every parameter tensor MODEL needs for inference, under explicit
names a JavaScript port can look up directly -- deliberately not the
positional :PARAMETERS list transformer.lisp uses for its own serialization,
so the browser-side port does not depend on group ordering."
  (ecase (parametric-model-kind model)
    (:multi-head-stack
     (list :kind "multi-head-stack"
           :d-model (parametric-model-d-model model)
           :d-ff (parametric-model-d-ff model)
           :num-heads (parametric-model-num-heads model)
           :num-layers (parametric-model-num-layers model)
           :feature-count (parametric-model-feature-count model)
           :feature-embeddings (trainer-values (parametric-model-feature-embeddings model))
           :scalar-weights (trainer-values (parametric-model-scalar-weights model))
           :scalar-bias (trainer-values (parametric-model-scalar-bias model))
           :layer-heads-wq (trainer-values (parametric-model-layer-heads-wq model))
           :layer-heads-wk (trainer-values (parametric-model-layer-heads-wk model))
           :layer-heads-wv (trainer-values (parametric-model-layer-heads-wv model))
           :layer-wo (trainer-values (parametric-model-layer-wo model))
           :layer-attention-gain (trainer-values (parametric-model-layer-attention-gain model))
           :layer-w1 (trainer-values (parametric-model-layer-w1 model))
           :layer-b1 (trainer-values (parametric-model-layer-b1 model))
           :layer-w2 (trainer-values (parametric-model-layer-w2 model))
           :layer-b2 (trainer-values (parametric-model-layer-b2 model))
           :layer-ffn-gain (trainer-values (parametric-model-layer-ffn-gain model))
           :final-norm-gain (trainer-values (parametric-model-final-norm-gain model))
           :output-weights (trainer-values (parametric-model-output-weights model))
           :output-bias (trainer-values (parametric-model-output-bias model))))
    (:legacy-single-head
     (list :kind "legacy-single-head"
           :d-model (parametric-model-d-model model)
           :d-ff (parametric-model-d-ff model)
           :feature-count (parametric-model-feature-count model)
           :feature-embeddings (trainer-values (parametric-model-feature-embeddings model))
           :scalar-weights (trainer-values (parametric-model-scalar-weights model))
           :scalar-bias (trainer-values (parametric-model-scalar-bias model))
           :wq (trainer-values (parametric-model-wq model))
           :wk (trainer-values (parametric-model-wk model))
           :wv (trainer-values (parametric-model-wv model))
           :wo (trainer-values (parametric-model-wo model))
           :w1 (trainer-values (parametric-model-w1 model))
           :b1 (trainer-values (parametric-model-b1 model))
           :w2 (trainer-values (parametric-model-w2 model))
           :b2 (trainer-values (parametric-model-b2 model))
           :output-weights (trainer-values (parametric-model-output-weights model))
           :output-bias (trainer-values (parametric-model-output-bias model))))))


(defun sarcoma-page-data (corpus weights)
  (let* ((source (parametric-open-corpus-source corpus))
         (metadata (parametric-source-metadata source))
         (schema (getf metadata :feature-schema))
         (artifact (predict-read-form weights))
         (pre (getf artifact :preprocessing))
         (result (predict-read-form (merge-pathnames (getf metadata :source-result) *sarcoma-root*)))
         (manifest (pathname (getf result :manifest)))
         (problem (read-form-file manifest))
         (spec (getf problem :data))
         (raw (read-dataset (merge-pathnames (getf spec :file) manifest) spec))
         (by-id (make-hash-table :test #'equal)) (records nil) (atlas nil))
    (unless (and (equalp schema (getf artifact :feature-schema))
                 (equalp (getf metadata :preprocessing) pre))
      (error "Corpus and model feature schema/preprocessing differ."))
    (dolist (row raw)
      (when (gethash (getf row :id) by-id) (error "Duplicate evidence ID."))
      (setf (gethash (getf row :id) by-id) row))
    (parametric-map-records source (lambda (record) (push record records)))
    (setf records (nreverse records))
    (dolist (record records)
      (let ((row (or (gethash (getf record :id) by-id) (error "Missing evidence record."))))
        (push (list :id (getf record :id) :label (getf record :label)
                    :cluster (getf record :cluster)
                    :x (first (getf record :target)) :y (second (getf record :target))
                    :evidence row
                    :raw-values (loop for f in schema collect (nth (getf f :column) (getf row :vector)))
                    :input (getf record :input)) atlas)))
    (setf atlas (nreverse atlas))
    (list :problem problem :atlas atlas
          :features
          (loop for f in schema for i from 0
                for mean in (getf pre :means) for scale in (getf pre :scales)
                for values = (mapcar (lambda (p) (nth i (getf p :raw-values))) atlas)
                collect (list :name (string-downcase (symbol-name (getf f :name)))
                              :label (substitute #\Space #\- (string-capitalize (symbol-name (getf f :name))))
                              :unit "feature units" :decimals 4
                              :raw-min (reduce #'min values) :raw-max (reduce #'max values)
                              :raw-mean (/ (reduce #'+ values) (length values))
                              :mean mean :scale scale :transformation (getf f :transformation)))
          :clusters
          (loop for c in (remove-duplicates (mapcar (lambda (p) (getf p :cluster)) atlas))
                for members = (remove-if-not (lambda (p) (= c (getf p :cluster))) atlas)
                for cx = (/ (reduce #'+ members :key (lambda (p) (getf p :x))) (length members))
                for cy = (/ (reduce #'+ members :key (lambda (p) (getf p :y))) (length members))
                for representative = (first (sort (copy-list members) #'< :key
                  (lambda (p) (+ (expt (- (getf p :x) cx) 2) (expt (- (getf p :y) cy) 2)))))
                collect (list :cluster c :name (getf representative :id)
                              :raw-values (getf representative :raw-values)))
          :model (preferences-model-json-plist (form-parametric-model (getf artifact :model))))))

(defun build-sarcoma-page (corpus weights output)
  (let* ((data (sarcoma-page-data corpus weights))
         (page (file-text (merge-pathnames "preferences-template.html" *sarcoma-directory*))))
    (loop for (marker key) on '("__ATLAS_POINTS__" :atlas "__FEATURES__" :features
                                "__CLUSTERS__" :clusters "__MODEL__" :model "__PROBLEM__" :problem)
          by #'cddr do
      (setf page (replace-marker page marker (with-output-to-string (s) (write-json-pretty (getf data key) s)))))
    (ensure-directories-exist output)
    (with-open-file (s output :direction :output :if-exists :supersede) (write-string page s))
    (format t "Wrote ~D atlas records with complete evidence and curves to ~A.~%" (length (getf data :atlas)) output)))
(defvar *sarcoma-page-run-main* t)
(when *sarcoma-page-run-main*
  (let ((args (cdr sb-ext:*posix-argv*)))
    (unless (= (length args) 3) (error "Expected CORPUS MODEL OUTPUT.html"))
    (apply #'build-sarcoma-page args)))
