;;;; basic.lisp -- unit tests for qprolog.  sbcl --non-interactive --load tests/basic.lisp
;;;; Each test: (goal expected-solutions) where solutions are the values of the listed
;;;; variables, in surface syntax (term->lisp) -- NIL means "no solution".
(in-package :cl-user)
(let ((*standard-output* (make-broadcast-stream)))
  (handler-bind ((warning #'muffle-warning))
    (load (merge-pathnames "../load.lisp" (or *load-truename* *load-pathname*)))))
(in-package :qp)

(defmacro prog- (&rest clauses) `(progn ,@(mapcar (lambda (c) `(add-clause ',(second c) ',(cddr c))) clauses)))
(defun defp (&rest clauses) (dolist (c clauses) (add-clause (car c) (cdr c))))

;; --- test program
(defp '((p 1)) '((p 2)) '((p 3))
      '((q ?x ?y) (p ?x) (p ?y) (< ?x ?y))
      '((cut1 ?x) (p ?x) !)
      '((cut2 ?x ?y) (p ?x) ! (p ?y))
      '((neg ?x) (\\+ (p ?x)))
      '((ite ?x ?r) (:or (< ?x 2) -> (unify ?r small) (unify ?r big)))
      '((ite2 ?x ?r) (:or (p ?x) -> (unify ?r yes) (unify ?r no)))
      '((cutin ?x) (:or (p ?x) (:and (p ?x) !)))
      '((len nil 0))
      '((len (?h . ?t) ?n) (len ?t ?m) (is ?n (+ ?m 1)))
      '((nrev nil nil))
      '((nrev (?h . ?t) ?r) (nrev ?t ?rt) (app ?rt (:l ?h) ?r))
      '((app nil ?l ?l))
      '((app (?h . ?t) ?l (?h . ?r)) (app ?t ?l ?r))
      '((count ?n ?n) !)
      '((count ?i ?n) (is ?j (+ ?i 1)) (count ?j ?n))
      '((mk 0 nil) !)
      '((mk ?n (?n . ?t)) (is ?m (- ?n 1)) (mk ?m ?t))
      '((f (g ?x ?x)))
      '((lst (:l a b c)))
      '((tailc (:l 1 2 :tail (h 3))))
      '((oncetest ?x) (once (p ?x)))
      '((ignoretest) (ignore (p 9)))
      '((fa) (forall (p ?x) (> ?x 0)))
      '((fb) (forall (p ?x) (> ?x 1)))
      '((callt ?g) (call ?g))
      '((call2 ?x) (call p ?x))
      '((cutcall ?x) (call (:and (p ?x) !)))
      '((deep ?x) (:or (p ?x) -> (:and (< ?x 3) !) true)))

(declare-dynamic '(/ d 1))
(declare-dynamic '(/ cnt 1))

(defvar *fails* 0)
(defvar *tests* 0)
(defvar *verbose* (sb-ext:posix-getenv "QP_VERBOSE"))   ; QP_VERBOSE=1 prints every test
(setf *read-default-float-format* 'double-float)
(defmacro test (goal vars expected)
  `(let ((got (handler-case (mapcar (lambda (s) (mapcar #'term->lisp s)) (solve-collect ',goal ',vars 1000))
                (error () '((:error))))))
     (incf *tests*)
     (if (equal (mapcar (lambda (s) (mapcar #'strip s)) got) ',expected)
         (when *verbose* (format t "ok   ~S  => ~S~%" ',goal got))
         (progn (incf *fails*)
                (format t "FAIL ~S~%   expected ~S~%   got      ~S~%" ',goal ',expected got)))))
(defun strip (x) (cond ((and (symbolp x) x (not (symbol-package x))) '_) ((consp x) (cons (strip (car x)) (strip (cdr x)))) (t x)))

(test (p ?x) (?x) ((1) (2) (3)))
(test (q ?x ?y) (?x ?y) ((1 2) (1 3) (2 3)))
(test (cut1 ?x) (?x) ((1)))
(test (cut2 ?x ?y) (?x ?y) ((1 1) (1 2) (1 3)))
(test (neg 4) () (nil))
(test (neg 2) () ())
(test (ite 1 ?r) (?r) ((small)))
(test (ite 5 ?r) (?r) ((big)))
(test (ite2 ?x ?r) (?x ?r) ((1 yes)))
(test (ite2 7 ?r) (?r) ((no)))
(test (cutin ?x) (?x) ((1) (2) (3) (1)))
(test (len (:l 1 2 3) ?n) (?n) ((3)))
(test (nrev (:l 1 2 3 4) ?r) (?r) (((4 3 2 1))))
(test (count 0 100000) () (nil))
(test (mk 5 ?l) (?l) (((5 4 3 2 1))))
(test (f ?y) (?y) (((g _ _))))
(test (f (g 1 ?z)) (?z) ((1)))
(test (f (g 1 2)) () ())
(test (lst ?x) (?x) (((:l a b c))))
(test (oncetest ?x) (?x) ((1)))
(test (ignoretest) () (nil))
(test (fa) () (nil))
(test (fb) () ())
(test (callt (p ?x)) (?x) ((1) (2) (3)))
(test (call2 ?x) (?x) ((1) (2) (3)))
(test (cutcall ?x) (?x) ((1)))
(test (deep ?x) (?x) ((1)))
;; builtins
(test (functor (f a b) ?n ?a) (?n ?a) ((f 2)))
(test (functor ?t g 2) (?t) (((g _ _))))
(test (functor (1 2) ?n ?a) (?n ?a) ((|[\|]| 2)))
(test (=.. (f a b) ?l) (?l) (((:l f a b))))
(test (=.. ?t (:l g 1)) (?t) (((g 1))))
(test (arg 2 (f a b) ?x) (?x) ((b)))
(test (arg ?n (f a b) ?x) (?n ?x) ((1 a) (2 b)))
(test (copy_term (f ?x ?y ?x) ?c) (?c) (((f _ _ _))))
(test (sort (:l 3 1 2 1) ?s) (?s) (((1 2 3))))
(test (msort (:l 3 1 2 1) ?s) (?s) (((1 1 2 3))))
(test (keysort (:l (- 2 a) (- 1 b) (- 2 c)) ?s) (?s) ((((- 1 b) (- 2 a) (- 2 c)))))
(test (compare ?o 1 2) (?o) ((<)))
(test (compare ?o (f a) (f a)) (?o) ((=)))
(test (compare ?o b a) (?o) ((>)))
(test (length ?l 2) (?l) (((_ _))))
(test (length (:l a b c) ?n) (?n) ((3)))
(test (between 1 3 ?x) (?x) ((1) (2) (3)))
(test (between 1 3 2) () (nil))
(test (numlist 1 5 ?l) (?l) (((1 2 3 4 5))))
(test (findall ?x (p ?x) ?l) (?l) (((1 2 3))))
(test (findall (- ?x ?y) (:and (p ?x) (p ?y) (< ?x ?y)) ?l) (?l) ((((- 1 2) (- 1 3) (- 2 3)))))
(test (findall ?x (:or (p ?x) (unify ?x z)) ?l) (?l) (((1 2 3 z))))
(test (is ?x (+ (* 2 3) (mod 7 4))) (?x) ((9)))
(test (is ?x (/ 7 2)) (?x) ((3.5d0)))
(test (is ?x (/ 8 2)) (?x) ((4)))
(test (is ?x (** 2 10)) (?x) ((1024)))
(test (is ?x (max 3 4.0)) (?x) ((4.0d0)))
(test (is 5 (+ 2 3)) () (nil))
(test (is 5.0 (+ 2 3)) () ())
(test (< 1 2) () (nil))
(test (== (f ?x) (f ?x)) () (nil))
(test (\\== (f ?x) (f ?y)) () (nil))
(test (unify (f ?x b) (f a ?y)) (?x ?y) ((a b)))
(test (atom_codes abc ?l) (?l) (((65 66 67))))
(test (atom_length hello ?n) (?n) ((5)))
(test (append ?x ?y (:l 1 2)) (?x ?y) ((nil (1 2)) ((1) (2)) ((1 2) nil)))
(test (member ?x (:l a b)) (?x) ((a) (b)))
(test (reverse (:l 1 2 3) ?r) (?r) (((3 2 1))))
(test (nth1 2 (:l a b c) ?x) (?x) ((b)))
(test (last (:l 1 2 3) ?x) (?x) ((3)))
(test (sum_list (:l 1 2 3) ?s) (?s) ((6)))
(test (\\+ (member z (:l a b))) () (nil))
(test (once (member ?x (:l a b))) (?x) ((a)))
(test (tailc ?x) (?x) (((:l 1 2 :tail (h 3)))))
;; assert / retract, logical update view
(test (:and (assertz (d 1)) (assertz (d 2)) (assertz (d 3))) () (nil))
(test (d ?x) (?x) ((1) (2) (3)))
(test (:and (d ?x) (assertz (d 9))) (?x) ((1) (2) (3)))
(test (retract (d 9)) () (nil nil nil))
(test (retract (d 9)) () ())
(test (:and (d ?x) (unify ?x 2) (retract (d ?x))) (?x) ((2)))
(test (findall ?x (d ?x) ?l) (?l) (((1 3))))
(test (retractall (d ?_)) () (nil))
(test (d ?x) (?x) ())
(test (:and (retractall (d ?_)) (asserta (d a)) (asserta (d b)) (findall ?x (d ?x) ?l)) (?l) (((:l b a))))
(test (:and (assertz (cnt 0)) (retract (cnt ?n)) (is ?m (+ ?n 1)) (assertz (cnt ?m)) (cnt ?k)) (?k) ((1)))
(test (:and (assertz (|:-| (dr ?x ?y) (:and (d ?x) (unify ?y ok)))) (dr ?a ?b)) (?a ?b) ((b ok) (a ok)))

;; catch / throw
(defp '((thr ?x) (throw (oops ?x)))
      '((ct1 ?r) (catch (thr 1) (oops ?x) (unify ?r (caught ?x))))
      '((ct2 ?r) (catch (p ?r) ?_e (unify ?r none)))
      '((ct3 ?r) (catch (:and (p ?x) (thr ?x)) (oops ?y) (unify ?r ?y)))
      '((ct4 ?r) (catch (catch (thr 2) (other) (unify ?r wrong)) (oops ?y) (unify ?r (outer ?y))))
      '((ct5 ?r) (catch (undefined_xyz) (error (existence_error ?a ?b) ?_) (unify ?r ?b)))
      '((ct6 ?r) (catch (:and (unify ?x 5) (thr ?x)) (oops ?y) (unify ?r ?y)))
      '((ct7 ?r) (catch (is ?x (/ 1 0)) (error ?e ?_) (unify ?r ?e))))
(test (ct1 ?r) (?r) (((caught 1))))
(test (ct2 ?r) (?r) ((1) (2) (3)))
(test (ct3 ?r) (?r) ((1)))
(test (ct4 ?r) (?r) (((outer 2))))
(test (ct5 ?r) (?r) (((/ undefined_xyz 0))))
(test (ct6 ?r) (?r) ((5)))
(test (ct7 ?r) (?r) (((evaluation_error zero_divisor))))
(test (:and (catch (findall ?x (:and (p ?x) (thr ?x)) ?_l) (oops ?y) (unify ?r ?y)) (unify ?r 1)) (?r) ((1)))
(test (thr 3) () ((:error)))
;; system predicates: shell, processes, environment, files, consult
(test (shell "exit 0") () (nil))
(test (shell "exit 2") () ())
(test (shell "exit 3" ?s) (?s) ((3)))
(test (shell_output "printf 'a b'" ?s ?o) (?s ?o) ((0 "a b")))
(test (process_run "printf" ("%s-%s" "x" 7) ((capture ?o)) ?s) (?s ?o) ((0 "x-7")))
(test (process_run "pwd" () ((cwd "/") (capture ?o)) ?s) (?s ?o) ((0 "/
")))
(test (process_run "sh" ("-c" "printf $V") ((env ("V=hi")) (capture ?o)) ?s) (?s ?o) ((0 "hi")))
(test (process_run "sh" ("-c" "kill -9 $$") ?s) (?s) ((137)))
(test (process_run "no-such-program-xyz" () ?s) () ((:error)))
(test (getenv "PATH" ?p) () (nil))
(test (getenv "NO_SUCH_VARIABLE_XYZ" ?p) () ())
(test (getenv_or "NO_SUCH_VARIABLE_XYZ" "dflt" ?v) (?v) (("dflt")))
(test (exists_directory "/") () (nil))
(test (exists_file "/") () ())
(test (exists_file "/no/such/file") () ())
(test (current_executable ?p) () (nil))
;; errors
(test (undefined_pred_xyz) () ((:error)))

(format t "~D tests, ~D passed, ~D failure~:P~%" *tests* (- *tests* *fails*) *fails*)
(sb-ext:exit :code (min 1 *fails*) :abort t)
