;;;; browse.lisp -- GENERATED from swi/browse.pl by bench/pl2lispy.lisp; do not edit.

(<- (top)
 (init 100 10 4
  ((:l a a a b b b b a a a a a b b a a a) (:l a a b b b b a a (:l a a) (:l b b))
   (:l a a a b (:l b a) b a b a))
  ?symbols)
 (randomize ?symbols ?rsymbols 21) !
 (investigate ?rsymbols
  (((star ?sa) ?b (star ?sb) ?b a (star ?sa) a (star ?sb) (star ?sa))
   ((star ?sa) (star ?sb) (star ?sb) (star ?sa) ((star ?sa)) ((star ?sb)))
   (_ _ (star _) (:l b a) (star _) _ _))))
(<- (init ?n ?m ?npats ?ipats ?result) (init ?n ?m ?m ?npats ?ipats ?result))
(<- (init 0 _ _ _ _ _) !)
(<- (init ?n ?i ?m ?npats ?ipats (?symb . ?rest)) (fill ?i nil ?l) (get_pats ?npats ?ipats ?ppats)
 (is ?j (- ?m ?i)) (fill ?j ((pattern ?ppats) . ?l) ?symb) (is ?n1 (- ?n 1))
 (:or (= ?i 0) -> (is ?i1 ?m) (is ?i1 (- ?i 1))) (init ?n1 ?i1 ?m ?npats ?ipats ?rest))
(<- (fill 0 ?l ?l) !)
(<- (fill ?n ?l ((dummy nil) . ?rest)) (is ?n1 (- ?n 1)) (fill ?n1 ?l ?rest))
(<- (randomize nil nil _) !)
(<- (randomize ?in (?x . ?out) ?rand) (list_to_length ?in ?lin) (is ?rand1 (mod (* ?rand 17) 251))
 (is ?n (mod ?rand1 ?lin)) (split ?n ?in ?x ?in1) (randomize ?in1 ?out ?rand1))
(<- (list_to_length ?list ?len) (list_to_length ?list 0 ?len))
(<- (list_to_length nil ?l ?l) !)
(<- (list_to_length (_ . ?t) ?l0 ?l) (is ?l1 (+ ?l0 1)) (list_to_length ?t ?l1 ?l))
(<- (split 0 (?x . ?xs) ?x ?xs) !)
(<- (split ?n (?x . ?xs) ?removedelt (?x . ?ys)) (is ?n1 (- ?n 1)) (split ?n1 ?xs ?removedelt ?ys))
(<- (investigate nil _) !)
(<- (investigate (?u . ?units) ?patterns) (property ?u pattern ?data)
 (p_investigate ?data ?patterns) (investigate ?units ?patterns))
(<- (get_pats ?npats ?ipats ?result) (get_pats ?npats ?ipats ?result ?ipats))
(<- (get_pats 0 _ nil _) !)
(<- (get_pats ?n (?x . ?xs) (?x . ?ys) ?ipats) (is ?n1 (- ?n 1)) (get_pats ?n1 ?xs ?ys ?ipats))
(<- (get_pats ?n nil ?ys ?ipats) (get_pats ?n ?ipats ?ys ?ipats))
(<- (property nil _ _) fail)
(<- (property (?prop . _) ?p ?val) (functor ?prop ?p _) ! (arg 1 ?prop ?val))
(<- (property (_ . ?rprops) ?p ?val) (property ?rprops ?p ?val))
(<- (p_investigate nil _))
(<- (p_investigate (?d . ?data) ?patterns) (p_match ?patterns ?d) (p_investigate ?data ?patterns))
(<- (p_match nil _))
(<- (p_match (?p . ?patterns) ?d) (:or (:and (match ?d ?p) fail) true) (p_match ?patterns ?d))
(<- (match nil nil) !)
(<- (match (?x . ?prest) (?y . ?srest)) (var ?y) ! (unify ?x ?y) (match ?prest ?srest))
(<- (match ?list (?y . ?rest)) (nonvar ?y) (unify ?y (star ?x)) ! ($concat ?x ?srest ?list)
 (match ?srest ?rest))
(<- (match (?x . ?prest) (?y . ?srest)) (:or (atom ?x) -> (unify ?x ?y) (match ?x ?y))
 (match ?prest ?srest))
(<- ($concat nil ?l ?l))
(<- ($concat (?x . ?l1) ?l2 (?x . ?l3)) ($concat ?l1 ?l2 ?l3))
