;;;; crypt.lisp -- GENERATED from swi/crypt.pl by bench/pl2lispy.lisp; do not edit.

(<- (top) (odd ?a) (even ?b) (even ?c) (even ?e) (mult (?c ?b ?a) ?e (?i ?h ?g ?f . ?x))
 (lefteven ?f) (odd ?g) (even ?h) (even ?i) (zero ?x) (lefteven ?d)
 (mult (?c ?b ?a) ?d (?l ?k ?j . ?y)) (lefteven ?j) (odd ?k) (even ?l) (zero ?y)
 (sum (?i ?h ?g ?f) (0 ?l ?k ?j) (?p ?o ?n ?m . ?z)) (odd ?m) (odd ?n) (even ?o) (even ?p)
 (zero ?z))
(<- (sum ?al ?bl ?cl) (sum ?al ?bl 0 ?cl))
(<- (sum (?a . ?al) (?b . ?bl) ?carry (?c . ?cl)) ! (is ?x (+ (+ ?a ?b) ?carry))
 (is ?c (mod ?x 10)) (is ?newcarry (// ?x 10)) (sum ?al ?bl ?newcarry ?cl))
(<- (sum nil ?bl 0 ?bl) !)
(<- (sum ?al nil 0 ?al) !)
(<- (sum nil (?b . ?bl) ?carry (?c . ?cl)) ! (is ?x (+ ?b ?carry)) (is ?newcarry (// ?x 10))
 (is ?c (mod ?x 10)) (sum nil ?bl ?newcarry ?cl))
(<- (sum (?a . ?al) nil ?carry (?c . ?cl)) ! (is ?x (+ ?a ?carry)) (is ?newcarry (// ?x 10))
 (is ?c (mod ?x 10)) (sum nil ?al ?newcarry ?cl))
(<- (sum nil nil ?carry (?carry)))
(<- (mult ?al ?d ?bl) (mult ?al ?d 0 ?bl))
(<- (mult (?a . ?al) ?d ?carry (?b . ?bl)) (is ?x (+ (* ?a ?d) ?carry)) (is ?b (mod ?x 10))
 (is ?newcarry (// ?x 10)) (mult ?al ?d ?newcarry ?bl))
(<- (mult nil _ ?carry (?c ?cend)) (is ?c (mod ?carry 10)) (is ?cend (// ?carry 10)))
(<- (zero nil))
(<- (zero (0 . ?l)) (zero ?l))
(<- (odd 1))
(<- (odd 3))
(<- (odd 5))
(<- (odd 7))
(<- (odd 9))
(<- (even 0))
(<- (even 2))
(<- (even 4))
(<- (even 6))
(<- (even 8))
(<- (lefteven 2))
(<- (lefteven 4))
(<- (lefteven 6))
(<- (lefteven 8))
