;;;; reducer.lisp -- GENERATED from swi/reducer.pl by bench/pl2lispy.lisp; do not edit.

(<- (top) (try (fac 3) ?_ans1) (try (quick (3 1 2)) ?_ans2))
(<- (try ?_inpexpr ?_anslist) (listify ?_inpexpr ?_list) (curry ?_list ?_curry)
 (t_reduce ?_curry ?_ans) (make_list ?_ans ?_anslist))
(<- (end ?x) (atom ?x) !)
(<- (end ?x) (== ?x nil))
(<- (list_functor_name ?name)
 (:or (atom ?name) -> (functor (_ . _) ?name _) (var ?name) -> (functor (_ . _) ?name _)))
(<- (t_def fac (?n) (cond (= ?n 0) 1 (* ?n (fac (- ?n 1))))))
(<-
 (t_def quick (?_l)
  (cond (= ?_l nil) nil (cond (= (tl ?_l) nil) ?_l (quick2 (split (hd ?_l) (tl ?_l)))))))
(<- (t_def quick2 (?_l) (my_append (quick (hd ?_l)) (quick (tl ?_l)))))
(<-
 (t_def split (?_e ?_l)
  (cond (= ?_l nil) ((?_e))
        (cond (=< (hd ?_l) ?_e) (inserthead (hd ?_l) (split ?_e (tl ?_l)))
              (inserttail (hd ?_l) (split ?_e (tl ?_l)))))))
(<- (t_def inserthead (?_e ?_l) (:l (:l ?_e :tail (hd ?_l)) :tail (tl ?_l))))
(<- (t_def inserttail (?_e ?_l) (:l (hd ?_l) ?_e :tail (tl ?_l))))
(<- (t_def my_append (?_a ?_b) (cond (= ?_a nil) ?_b (:l (hd ?_a) :tail (my_append (tl ?_a) ?_b)))))
(<- (t_reduce ?_expr ?_ans) (atomic ?_expr) ! (unify ?_ans ?_expr))
(<- (t_reduce (?_y ?_x . ?lf) (?_yr ?_xr . ?lf)) (list_functor_name ?lf) (t_reduce ?_x ?_xr) !
 (t_reduce ?_y ?_yr) !)
(<- (t_reduce ?_expr ?_ans) (t_append ?_next ?_red ?_form ?_expr) (t_redex ?_form ?_red) !
 (t_reduce ?_next ?_ans) !)
(<- (t_append ?_link ?_link ?_l ?_l))
(<- (t_append (?_a . ?_l1) ?_link ?_l2 (?_a . ?_l3)) (t_append ?_l1 ?_link ?_l2 ?_l3))
(<- (t_redex (?_x ?_g ?_f ?_k . sp) ((?_xr . ?_g) (?_xr . ?_f) . ?_k)) (t_reduce ?_x ?_xr))
(<- (t_redex (?_x ?_g ?_f ?_k . bp) ((?_x . ?_g) ?_f . ?_k)))
(<- (t_redex (?_x ?_g ?_f ?_k . cp) (?_g (?_x . ?_f) . ?_k)))
(<- (t_redex (?_x ?_g ?_f . s) ((?_xr . ?_g) ?_xr . ?_f)) (t_reduce ?_x ?_xr))
(<- (t_redex (?_x ?_g ?_f . b) ((?_x . ?_g) . ?_f)))
(<- (t_redex (?_x ?_g ?_f . c) (?_g ?_x . ?_f)))
(<- (t_redex (?_y ?_x . k) ?_x))
(<- (t_redex (?_x . i) ?_x))
(<- (t_redex (?_elsepart ?_ifpart ?_cond . cond) ?_ifpart) (t_reduce ?_cond ?_bool)
 (unify ?_bool true) !)
(<- (t_redex (?_elsepart ?_ifpart ?_cond . cond) ?_elsepart))
(<- (t_redex (?_f . apply) ?_fr) (t_reduce ?_f ?_fr))
(<- (t_redex (?_arg . hd) ?_x) (list_functor_name ?lf) (t_reduce ?_arg (?_y ?_x . ?lf)))
(<- (t_redex (?_arg . tl) ?_y) (list_functor_name ?lf) (t_reduce ?_arg (?_y ?_x . ?lf)))
(<- (t_redex (?_y ?_x . ?_op) ?_res) (end ?_op) (my_member ?_op (:l + - * // mod))
 (t_reduce ?_x ?_xres) (t_reduce ?_y ?_yres) (number ?_xres) (number ?_yres)
 (eval ?_op ?_res ?_xres ?_yres))
(<- (t_redex (?_y ?_x . ?_test) ?_res) (end ?_test) (my_member ?_test (:l < > =< >= |=\\=| |=:=|))
 (t_reduce ?_x ?_xres) (t_reduce ?_y ?_yres) (number ?_xres) (number ?_yres)
 (:or (relop ?_test ?_xres ?_yres) -> (unify ?_res true) (unify ?_res false)) !)
(<- (t_redex (?_y ?_x . =) ?_res) (t_reduce ?_x ?_xres) (t_reduce ?_y ?_yres)
 (:or (unify ?_xres ?_yres) -> (unify ?_res true) (unify ?_res false)) !)
(<- (t_redex (?_x . ?_op) ?_res) (end ?_op) (my_member ?_op (:l -)) (t_reduce ?_x ?_xres)
 (number ?_xres) (eval1 ?_op ?_t ?_xres))
(<- (t_redex ?_in ?_out) (my_append ?_par ?_func ?_in) (end ?_func) (t_def ?_func ?_args ?_expr)
 (t ?_args ?_expr ?_def) (my_append ?_par ?_def ?_out))
(<- (eval + ?c ?a ?b) (is ?c (+ ?a ?b)))
(<- (eval - ?c ?a ?b) (is ?c (- ?a ?b)))
(<- (eval * ?c ?a ?b) (is ?c (* ?a ?b)))
(<- (eval // ?c ?a ?b) (is ?c (// ?a ?b)))
(<- (eval mod ?c ?a ?b) (is ?c (mod ?a ?b)))
(<- (eval1 - ?c ?a) (is ?c (- ?a)))
(<- (relop < ?a ?b) (< ?a ?b))
(<- (relop > ?a ?b) (> ?a ?b))
(<- (relop =< ?a ?b) (<= ?a ?b))
(<- (relop >= ?a ?b) (>= ?a ?b))
(<- (relop |=\\=| ?a ?b) (/= ?a ?b))
(<- (relop |=:=| ?a ?b) (= ?a ?b))
(<- (t ?_argvars ?_expr ?_trans) (listify ?_expr ?_list) (curry ?_list ?_curry)
 (t_argvars ?_argvars ?_curry ?_trans) !)
(<- (t_argvars nil ?_trans ?_trans))
(<- (t_argvars (?_x . ?_argvars) ?_in ?_trans) (t_argvars ?_argvars ?_in ?_mid)
 (t_vars ?_mid ?_vars) (t_trans ?_x ?_mid ?_vars ?_trans))
(<- (curry ?_a ?_a) (:or (var ?_a) (atomic ?_a)) !)
(<- (curry (?_func . ?_args) ?_cargs) (currylist ?_args ?_cargs ?_func))
(<- (currylist nil ?_link ?_link) !)
(<- (currylist (?_a . ?_args) ?_cargs ?_link) (curry ?_a ?_c)
 (currylist ?_args ?_cargs (?_c . ?_link)))
(<- (t_vars ?_v ((?_v))) (var ?_v) !)
(<- (t_vars ?_a (nil)) (atomic ?_a) !)
(<- (t_vars (?_func) (nil)) (atomic ?_func) !)
(<- (t_vars (?_arg . ?_func) (?_g (?_g1 . ?_af1) (?_g2 . ?_af2))) (t_vars ?_arg (?_g1 . ?_af1))
 (t_vars ?_func (?_g2 . ?_af2)) (unionv ?_g1 ?_g2 ?_g))
(<- (t_trans ?_x ?_a _ (?_a . k)) (:or (atomic ?_a) (:and (var ?_a) (|\\==| ?_a ?_x))) !)
(<- (t_trans ?_x ?_y _ i) (== ?_x ?_y) !)
(<- (t_trans ?_x ?_e (?_ve . _) (?_e . k)) (notinv ?_x ?_ve))
(<- (t_trans ?_x (?_f . ?_e) (?_vef ?_sf ?_se) ?_res) (unify ?_sf (?_vf . _))
 (unify ?_se (?_ve . ?_other))
 (:or (end ?_e) (:and (unify ?_other (_ (?_ve1 . _))) (|\\==| ?_ve1 nil)))
 (t_rule1 ?_x ?_e ?_ve ?_se ?_f ?_vf ?_sf ?_res))
(<- (t_trans ?_x (?_g ?_f . ?_e) (?_vefg ?_sg ?_sef) ?_res) (unify ?_sg (?_vg . _))
 (unify ?_sef (?_vef ?_sf ?_se)) (unify ?_se (?_ve . _)) (unify ?_sf (?_vf . _))
 (t_rule2 ?_x ?_e ?_f ?_vf ?_sf ?_g ?_vg ?_sg ?_res))
(<- (t_rule1 ?_x ?_e ?_ve ?_se ?_f ?_vf ?_sf ?_e) (notinv ?_x ?_ve) (== ?_x ?_f) !)
(<- (t_rule1 ?_x ?_e ?_ve ?_se ?_f ?_vf ?_sf (?_resf ?_e . b)) (notinv ?_x ?_ve) (inv ?_x ?_vf)
 (|\\==| ?_x ?_f) ! (t_trans ?_x ?_f ?_sf ?_resf))
(<- (t_rule1 ?_x ?_e ?_ve ?_se ?_f ?_vf ?_sf (?_f ?_rese . c)) (notinv ?_x ?_vf) !
 (t_trans ?_x ?_e ?_se ?_rese))
(<- (t_rule1 ?_x ?_e ?_ve ?_se ?_f ?_vf ?_sf (?_resf ?_rese . s)) (t_trans ?_x ?_e ?_se ?_rese)
 (t_trans ?_x ?_f ?_sf ?_resf))
(<- (t_rule2 ?_x ?_e ?_f ?_vf ?_sf ?_g ?_vg ?_sg (?_g ?_e . c)) (== ?_x ?_f) (notinv ?_x ?_vg) !)
(<- (t_rule2 ?_x ?_e ?_f ?_vf ?_sf ?_g ?_vg ?_sg (?_resg ?_e . s)) (== ?_x ?_f) !
 (t_trans ?_x ?_g ?_sg ?_resg))
(<- (t_rule2 ?_x ?_e ?_f ?_vf ?_sf ?_g ?_vg ?_sg (?_g ?_resf ?_e . cp)) (inv ?_x ?_vf)
 (notinv ?_x ?_vg) ! (t_trans ?_x ?_f ?_sf ?_resf))
(<- (t_rule2 ?_x ?_e ?_f ?_vf ?_sf ?_g ?_vg ?_sg (?_resg ?_resf ?_e . sp)) (inv ?_x ?_vf) !
 (t_trans ?_x ?_f ?_sf ?_resf) (t_trans ?_x ?_g ?_sg ?_resg))
(<- (t_rule2 ?_x ?_e ?_f ?_vf ?_sf ?_g ?_vg ?_sg (?_f . ?_e)) (== ?_x ?_g) !)
(<- (t_rule2 ?_x ?_e ?_f ?_vf ?_sf ?_g ?_vg ?_sg (?_resg ?_f ?_e . bp))
 (t_trans ?_x ?_g ?_sg ?_resg))
(<- (make_list ?_a ?_a) (atomic ?_a))
(<- (make_list (?_b ?_a . ?lf) (?_a . ?_rb)) (list_functor_name ?lf) (make_list ?_b ?_rb))
(<- (listify ?_x ?_x) (:or (var ?_x) (atomic ?_x)) !)
(<- (listify ?_expr (?_op . ?_largs)) (functor ?_expr ?_op ?n) (listify_list 1 ?n ?_expr ?_largs))
(<- (listify_list ?i ?n _ nil) (> ?i ?n) !)
(<- (listify_list ?i ?n ?_expr (?_la . ?_largs)) (<= ?i ?n) ! (arg ?i ?_expr ?_a)
 (listify ?_a ?_la) (is ?i1 (+ ?i 1)) (listify_list ?i1 ?n ?_expr ?_largs))
(<- (my_member ?x (?x . _)))
(<- (my_member ?x (_ . ?l)) (my_member ?x ?l))
(<- (my_append nil ?l ?l))
(<- (my_append (?x . ?l1) ?l2 (?x . ?l3)) (my_append ?l1 ?l2 ?l3))
(<- (intersectv nil _ nil))
(<- (intersectv (?a . ?s1) ?s2 ?s) (intersectv_2 ?s2 ?a ?s1 ?s))
(<- (intersectv_2 nil _ _ nil))
(<- (intersectv_2 (?b . ?s2) ?a ?s1 ?s) (compare ?order ?a ?b)
 (intersectv_3 ?order ?a ?s1 ?b ?s2 ?s))
(<- (intersectv_3 < _ ?s1 ?b ?s2 ?s) (intersectv_2 ?s1 ?b ?s2 ?s))
(<- (intersectv_3 = ?a ?s1 _ ?s2 (?a . ?s)) (intersectv ?s1 ?s2 ?s))
(<- (intersectv_3 > ?a ?s1 _ ?s2 ?s) (intersectv_2 ?s2 ?a ?s1 ?s))
(<- (intersectv_list nil nil))
(<- (intersectv_list (?ins . ?sets) ?outs) (intersectv_list ?sets ?ins ?outs))
(<- (intersectv_list nil ?_dcg_56 ?_dcg_57) (unify ?_dcg_56 ?_dcg_57))
(<- (intersectv_list (?s . ?sets) ?_dcg_58 ?_dcg_59) (intersectv ?s ?_dcg_58 ?_dcg_60)
 (intersectv_list ?sets ?_dcg_60 ?_dcg_59))
(<- (diffv nil _ nil))
(<- (diffv (?a . ?s1) ?s2 ?s) (diffv_2 ?s2 ?a ?s1 ?s))
(<- (diffv_2 nil ?a ?s1 (?a . ?s1)))
(<- (diffv_2 (?b . ?s2) ?a ?s1 ?s) (compare ?order ?a ?b) (diffv_3 ?order ?a ?s1 ?b ?s2 ?s))
(<- (diffv_3 < ?a ?s1 ?b ?s2 (?a . ?s)) (diffv ?s1 (?b . ?s2) ?s))
(<- (diffv_3 = ?a ?s1 _ ?s2 ?s) (diffv ?s1 ?s2 ?s))
(<- (diffv_3 > ?a ?s1 _ ?s2 ?s) (diffv_2 ?s2 ?a ?s1 ?s))
(<- (unionv nil ?s2 ?s2))
(<- (unionv (?a . ?s1) ?s2 ?s) (unionv_2 ?s2 ?a ?s1 ?s))
(<- (unionv_2 nil ?a ?s1 (?a . ?s1)))
(<- (unionv_2 (?b . ?s2) ?a ?s1 ?s) (compare ?order ?a ?b) (unionv_3 ?order ?a ?s1 ?b ?s2 ?s))
(<- (unionv_3 < ?a ?s1 ?b ?s2 (?a . ?s)) (unionv_2 ?s1 ?b ?s2 ?s))
(<- (unionv_3 = ?a ?s1 _ ?s2 (?a . ?s)) (unionv ?s1 ?s2 ?s))
(<- (unionv_3 > ?a ?s1 ?b ?s2 (?b . ?s)) (unionv_2 ?s2 ?a ?s1 ?s))
(<- (subsetv nil _))
(<- (subsetv (?a . ?s1) (?b . ?s2)) (compare ?order ?a ?b) (subsetv_2 ?order ?a ?s1 ?s2))
(<- (subsetv_2 = _ ?s1 ?s2) (subsetv ?s1 ?s2))
(<- (subsetv_2 > ?a ?s1 ?s2) (subsetv (?a . ?s1) ?s2))
(<- (small_subsetv nil _))
(<- (small_subsetv (?a . ?s1) ?s2) (inv ?a ?s2) (small_subsetv ?s1 ?s2))
(<- (inv ?a (?b . ?s)) (compare ?order ?a ?b) (inv_2 ?order ?a ?s))
(<- (inv_2 = _ _))
(<- (inv_2 > ?a ?s) (inv ?a ?s))
(<- (notinv ?a ?s) (notinv_2 ?s ?a))
(<- (notinv_2 nil _))
(<- (notinv_2 (?b . ?s) ?a) (compare ?order ?a ?b) (notinv_3 ?order ?a ?s))
(<- (notinv_3 < _ _))
(<- (notinv_3 > ?a ?s) (notinv_2 ?s ?a))
