;;;; sendmore.lisp -- GENERATED from swi/sendmore.pl by bench/pl2lispy.lisp; do not edit.

(<- (top) (digit ?d) (digit ?e) (/= ?d ?e) (sumdigit 0 ?d ?e ?y ?c1) (digit ?n) (/= ?n ?y)
 (/= ?n ?e) (/= ?n ?d) (digit ?r) (/= ?r ?n) (/= ?r ?y) (/= ?r ?e) (/= ?r ?d)
 (sumdigit ?c1 ?n ?r ?e ?c2) (digit ?o) (/= ?o ?r) (/= ?o ?n) (/= ?o ?y) (/= ?o ?e) (/= ?o ?d)
 (sumdigit ?c2 ?e ?o ?n ?c3) (leftdigit ?s) (/= ?s ?o) (/= ?s ?r) (/= ?s ?n) (/= ?s ?y) (/= ?s ?e)
 (/= ?s ?d) (leftdigit ?m) (/= ?m ?s) (/= ?m ?o) (/= ?m ?r) (/= ?m ?n) (/= ?m ?y) (/= ?m ?e)
 (/= ?m ?d) (sumdigit ?c3 ?s ?m ?o ?m) fail)
(<- (top))
(<- (sumdigit ?c ?a ?b ?s ?d) (is ?x (+ (+ ?c ?a) ?b))
 (:or (< ?x 10) -> (:and (unify ?s ?x) (unify ?d 0)) (:and (is ?s (- ?x 10)) (unify ?d 1))))
(<- (digit 0))
(<- (digit 1))
(<- (digit 2))
(<- (digit 3))
(<- (digit 4))
(<- (digit 5))
(<- (digit 6))
(<- (digit 7))
(<- (digit 8))
(<- (digit 9))
(<- (leftdigit 1))
(<- (leftdigit 2))
(<- (leftdigit 3))
(<- (leftdigit 4))
(<- (leftdigit 5))
(<- (leftdigit 6))
(<- (leftdigit 7))
(<- (leftdigit 8))
(<- (leftdigit 9))
