;;;; simple_analyzer.lisp -- GENERATED from swi/simple_analyzer.pl by bench/pl2lispy.lisp; do not edit.

(<- (top) (main _))
(<- (main ?table)
 (analyze_strees
  ((stree (/ main 0) (|:-| main (|;| (|,| (qsort (1 2) ?l nil) true) fail)) (|:-| main true) nil 1)
   (stree (/ qsort 3)
    (|:-| (qsort ?u ?p ?q)
     (|;|
      (|,| (= ?u (?n . ?o))
       (|,| (part ?o ?n ?r ?s) (|,| (qsort ?s ?t ?q) (|,| (qsort ?r ?p (?n . ?t)) true))))
      (|;| (|,| (= ?u nil) (|,| (= ?q ?p) true)) fail)))
    (|:-| (qsort _ _ _) true) nil 1)
   (stree (/ part 4)
    (|:-| (part ?w ?x ?y ?z)
     (|;| (|,| ($cut_load ?a1) (|,| ($cut_part/4_1 ?w ?x ?y ?z ?a1) true)) fail))
    (|:-| (part _ _ _ _) true)
    ((stree (/ $cut_part/4_1 5)
      (|:-| ($cut_part/4_1 ?i1 ?e1 ?f1 ?g1 ?h1)
       (|;| (|,| (= ?i1 (?c1 . ?d1)) (|,| ($fac_$cut_part/4_1/5_2 ?d1 ?e1 ?f1 ?g1 ?h1 ?c1) true))
        (|;| (|,| (= ?i1 nil) (|,| (= ?f1 nil) (|,| (= ?g1 nil) true))) fail)))
      (|:-| ($cut_part/4_1 _ _ _ _ _) true)
      ((stree (/ $fac_$cut_part/4_1/5_2 6)
        (|:-| ($fac_$cut_part/4_1/5_2 ?k1 ?l1 ?q1 ?o1 ?p1 ?m1)
         (|;|
          (|,| (= ?q1 (?m1 . ?n1))
           (|,| (=< ?m1 ?l1) (|,| ($cut_shallow ?p1) (|,| (part ?k1 ?l1 ?n1 ?o1) true))))
          (|;| (|,| (= ?o1 (?m1 . ?r1)) (|,| (part ?k1 ?l1 ?q1 ?r1) true)) fail)))
        (|:-| ($fac_$cut_part/4_1/5_2 _ _ _ _ _ _) true) nil 1))
      1))
    1))
  ?table))
(<- (analyze_strees ?strees ?outtable) (init_strees ?strees _ ?table) (seal ?table)
 (analyze_closure ?strees ?table ?outtable))
(<- (analyze_closure ?strees ?intable ?outtable)
 (traverse_strees ?strees ?intable ?midtable 0 ?changes)
 (analyze_closure ?strees ?midtable ?outtable ?changes))
(<- (analyze_closure ?strees ?intable ?intable ?n) (<= ?n 0) !)
(<- (analyze_closure ?strees ?intable ?outtable ?n) (> ?n 0) !
 (analyze_closure ?strees ?intable ?outtable))
(<- (init_strees nil ?_4 ?_4) true)
(<- (init_strees (?_12 . ?_13) ?_4 ?_5) (unify ?_12 (stree ?_14 (|:-| ?_15 ?_16) ?_17 ?_18 ?_19))
 (bottom_call ?_14 ?_20) (table_command (get ?_14 ?_20) ?_4 ?_23) (init_disj ?_16 ?_23 ?_24)
 (init_strees ?_18 ?_24 ?_25) (init_strees ?_13 ?_25 ?_5) true)
(<- (init_conj true ?_4 ?_4) true)
(<- (init_conj (|,| ?_12 ?_13) ?_4 ?_5) (init_goal ?_12 ?_4 ?_16) (init_conj ?_13 ?_16 ?_5) true)
(<- (init_disj fail ?_4 ?_4) true)
(<- (init_disj (|;| ?_12 ?_13) ?_4 ?_5) (init_conj ?_12 ?_4 ?_16) (init_disj ?_13 ?_16 ?_5) true)
(<- (init_goal ?_3 ?_4 ?_5) (call_p ?_3) ! (functor ?_3 ?_12 ?_13) (bottom_call (/ ?_12 ?_13) ?_14)
 (table_command (get (/ ?_12 ?_13) ?_14) ?_4 ?_5) true)
(<- (init_goal ?_3 ?_4 ?_4) (unify_p ?_3) ! true)
(<- (traverse_strees nil ?_4 ?_4 ?_6 ?_6) true)
(<- (traverse_strees (?_14 . ?_15) ?_4 ?_5 ?_6 ?_7)
 (unify ?_14 (stree ?_16 (|:-| ?_17 ?_18) ?_19 ?_20 ?_21))
 (traverse_disj ?_17 ?_18 ?_4 ?_26 ?_6 ?_27) (traverse_strees ?_20 ?_26 ?_28 ?_27 ?_29)
 (traverse_strees ?_15 ?_28 ?_5 ?_29 ?_7) true)
(<- (traverse_disj ?_3 fail ?_5 ?_5 ?_7 ?_7) true)
(<- (traverse_disj ?_3 (|;| ?_15 ?_16) ?_5 ?_6 ?_7 ?_8) (traverse_conj ?_3 ?_15 ?_5 ?_22 ?_7 ?_23)
 (traverse_disj ?_3 ?_16 ?_22 ?_6 ?_23 ?_8) true)
(<- (traverse_conj ?_3 ?_4 ?_5 ?_6 ?_7 ?_8) (varset ?_3 ?_24) (functor ?_3 ?_15 ?_16)
 (table_command (get (/ ?_15 ?_16) ?_17) ?_5 ?_25) (get_entry_modes uninit ?_3 ?_17 ?_26)
 (get_entry_modes ground ?_3 ?_17 ?_27)
 (traverse_conj ?_4 ?_25 ?_6 ?_7 ?_8 ?_27 ?_28 ?_26 ?_29 ?_24 ?_30) true)
(<- (traverse_conj true ?_4 ?_4 ?_6 ?_6 ?_8 ?_8 ?_10 ?_10 ?_12 ?_12) true)
(<- (traverse_conj (|,| ?_20 ?_21) ?_4 ?_5 ?_6 ?_7 ?_8 ?_9 ?_10 ?_11 ?_12 ?_13) (varset ?_20 ?_32)
 (update_goal ?_20 ?_32 ?_4 ?_33 ?_6 ?_34 ?_8 ?_35 ?_10 ?_36 ?_12 ?_37) (unionv ?_32 ?_37 ?_38)
 (traverse_conj ?_21 ?_33 ?_5 ?_34 ?_7 ?_35 ?_9 ?_36 ?_11 ?_38 ?_13) true)
(<- (update_goal ?_3 ?_4 ?_5 ?_5 ?_7 ?_7 ?_9 ?_10 ?_11 ?_12 ?_13 ?_13) (split_unify ?_3 ?_21 ?_27)
 (var ?_21) (nonvar ?_27) (varset ?_27 ?_28) (subsetv ?_28 ?_9) ! (set_command (add ?_21) ?_9 ?_10)
 (set_command (sub ?_21) ?_11 ?_12) true)
(<- (update_goal ?_3 ?_4 ?_5 ?_5 ?_7 ?_7 ?_9 ?_9 ?_11 ?_12 ?_13 ?_13) (split_unify ?_3 ?_21 ?_30)
 (var ?_21) (nonvar ?_30) (inv ?_21 ?_11) ! (diffv ?_4 ?_13 ?_31) (diffv ?_31 ?_9 ?_22)
 (set_command (add_set ?_22) ?_11 ?_32) (set_command (sub ?_21) ?_32 ?_33)
 (intersectv ?_4 ?_13 ?_23) (set_command (sub_set ?_23) ?_33 ?_12) true)
(<- (update_goal ?_3 ?_4 ?_5 ?_5 ?_7 ?_7 ?_9 ?_10 ?_11 ?_12 ?_13 ?_13) (split_unify ?_3 ?_27 ?_28)
 (var ?_27) (inv ?_27 ?_9) ! (set_command (add_set ?_4) ?_9 ?_10)
 (set_command (sub_set ?_4) ?_11 ?_12) true)
(<- (update_goal ?_3 ?_4 ?_5 ?_5 ?_7 ?_7 ?_9 ?_9 ?_11 ?_12 ?_13 ?_13) (unify_p ?_3) !
 (set_command (sub_set ?_4) ?_11 ?_12) true)
(<- (update_goal ?_3 ?_4 ?_5 ?_6 ?_7 ?_8 ?_9 ?_9 ?_11 ?_12 ?_13 ?_13) (call_p ?_3) !
 (goal_dupset ?_3 ?_33) (var_args ?_3 ?_34) (functor ?_3 ?_22 ?_23) (functor ?_35 ?_22 ?_23)
 (create_new_call 1 ?_23 ?_9 ?_34 ?_33 ?_11 ?_13 ?_3 ?_35)
 (update_table (/ ?_22 ?_23) ?_35 ?_5 ?_6 ?_7 ?_8) (set_command (sub_set ?_4) ?_11 ?_12) true)
(<- (update_table (/ ?_15 ?_16) ?_4 ?_5 ?_6 ?_7 ?_8)
 (table_command (get (/ ?_15 ?_16) ?_18) ?_5 ?_24) (lub_call ?_18 ?_4 ?_19) (|\\==| ?_18 ?_19) !
 (table_command (set (/ ?_15 ?_16) ?_19) ?_24 ?_6) (is ?_8 (+ ?_7 1)) true)
(<- (update_table (/ ?_15 ?_16) ?_4 ?_5 ?_5 ?_7 ?_7))
(<- (create_new_call ?i ?ar _ _ _ _ _ _ _) (> ?i ?ar) !)
(<- (create_new_call ?i ?ar ?gnd ?varargs ?dupvars ?uni ?sofar ?goal ?call) (<= ?i ?ar) !
 (arg ?i ?goal ?x) (arg ?i ?call ?y) (ground_flag ?x ?gnd ?gf) (membership_flag ?x ?varargs ?vf)
 (membership_flag ?x ?dupvars ?df) (membership_flag ?x ?uni ?uf) (membership_flag ?x ?sofar ?sf)
 (create_argument ?gf ?vf ?df ?uf ?sf ?y) (is ?i1 (+ ?i 1))
 (create_new_call ?i1 ?ar ?gnd ?varargs ?dupvars ?uni ?sofar ?goal ?call))
(<- (lub unknown ?x ?x) !)
(<- (lub ?x unknown ?x) !)
(<- (lub any _ any) !)
(<- (lub _ any any) !)
(<- (lub uninit uninit uninit) !)
(<- (lub ground ground ground) !)
(<- (lub uninit ground any) !)
(<- (lub ground uninit any) !)
(<- (bottom unknown))
(<- (create_argument yes _ _ _ _ ground) !)
(<- (create_argument no yes no yes _ uninit) !)
(<- (create_argument no yes no _ no uninit) !)
(<- (create_argument no yes _ no yes any) !)
(<- (create_argument no yes yes _ _ any) !)
(<- (create_argument no no _ _ _ any) !)
(<- (lub_call ?call1 ?call2 ?lub) (functor ?call1 ?na ?ar) (functor ?call2 ?na ?ar)
 (functor ?lub ?na ?ar) (lub_call 1 ?ar ?call1 ?call2 ?lub))
(<- (lub_call ?i ?ar _ _ _) (> ?i ?ar) !)
(<- (lub_call ?i ?ar ?call1 ?call2 ?lub) (<= ?i ?ar) ! (arg ?i ?call1 ?x1) (arg ?i ?call2 ?x2)
 (arg ?i ?lub ?x) (lub ?x1 ?x2 ?x) (is ?i1 (+ ?i 1)) (lub_call ?i1 ?ar ?call1 ?call2 ?lub))
(<- (bottom_call (/ ?na ?ar) ?bottom) (functor ?bottom ?na ?ar) (bottom_call 1 ?ar ?bottom))
(<- (bottom_call ?i ?ar ?bottom) (> ?i ?ar) !)
(<- (bottom_call ?i ?ar ?bottom) (<= ?i ?ar) ! (bottom ?b) (arg ?i ?bottom ?b) (is ?i1 (+ ?i 1))
 (bottom_call ?i1 ?ar ?bottom))
(<- (lattice_modes_call (/ ?na ?ar) ?table (|:-| ?head ?formula)) (functor ?head ?na ?ar)
 (get ?table (/ ?na ?ar) ?value) (lattice_modes_call 1 ?ar ?value ?head ?formula true))
(<- (lattice_modes_call ?i ?ar _ _ ?link ?link) (> ?i ?ar) !)
(<- (lattice_modes_call ?i ?ar ?value ?head ?formula ?link) (<= ?i ?ar) ! (arg ?i ?value ?t)
 (arg ?i ?head ?x) (lattice_modes_arg ?t ?x ?formula ?mid) (is ?i1 (+ ?i 1))
 (lattice_modes_call ?i1 ?ar ?value ?head ?mid ?link))
(<- (lattice_modes_arg uninit ?x (|,| (uninit ?x) ?link) ?link) !)
(<- (lattice_modes_arg ground ?x (|,| (ground ?x) ?link) ?link) !)
(<- (lattice_modes_arg ?other ?x ?link ?link))
(<- (get (node ?n ?w ?l ?r) ?i ?v) (get ?n ?w ?l ?r ?i ?v))
(<- (get ?n ?v _ _ ?i ?v) (unify ?i ?n) !)
(<- (get ?n _ ?l ?r ?i ?v) (compare ?order ?i ?n) (get ?order ?i ?v ?l ?r))
(<- (get < ?i ?v ?l _) (get ?l ?i ?v))
(<- (get > ?i ?v _ ?r) (get ?r ?i ?v))
(<- (set leaf ?i ?v (node ?i ?v leaf leaf)))
(<- (set (node ?n ?w ?l ?r) ?i ?v (node ?n ?nw ?nl ?nr)) (compare ?order ?i ?n)
 (set_2 ?order ?i ?v ?w ?l ?r ?nw ?nl ?nr))
(<- (set_2 < ?i ?v ?w ?l ?r ?w ?nl ?r) (set ?l ?i ?v ?nl))
(<- (set_2 = ?i ?v _ ?l ?r ?v ?l ?r))
(<- (set_2 > ?i ?v ?w ?l ?r ?w ?l ?nr) (set ?r ?i ?v ?nr))
(<- (seal leaf))
(<- (seal (node _ _ ?l ?r)) (seal ?l) (seal ?r))
(<- (membership_flag ?x ?set yes) (inv ?x ?set) !)
(<- (membership_flag ?x ?set no))
(<- (ground_flag ?x ?ground yes) (varset ?x ?set) (subsetv ?set ?ground) !)
(<- (ground_flag ?x ?ground no))
(<- (get_entry_modes ?type ?head ?value ?typeset) (functor ?head ?na ?ar)
 (get_entry_modes ?type 1 ?ar ?head ?value ?bag) (sort ?bag ?typeset))
(<- (get_entry_modes _ ?i ?ar _ _ nil) (> ?i ?ar) !)
(<- (get_entry_modes ?t ?i ?ar ?head ?value (?x . ?bag)) (<= ?i ?ar) (arg ?i ?value ?t) !
 (arg ?i ?head ?x) (is ?i1 (+ ?i 1)) (get_entry_modes ?t ?i1 ?ar ?head ?value ?bag))
(<- (get_entry_modes ?t ?i ?ar ?head ?value ?bag) (<= ?i ?ar) ! (is ?i1 (+ ?i 1))
 (get_entry_modes ?t ?i1 ?ar ?head ?value ?bag))
(<- (var_args ?goal ?set) (functor ?goal _ ?ar) (filter_vars ?ar ?goal ?bag) (sort ?bag ?set))
(<- (filter_vars ?ar ?goal ?vs) (filter_vars ?ar ?goal ?vs nil))
(<- (filter_vars ?n ?goal ?_dcg_61 ?_dcg_62) (<= ?n 0) (unify ?_dcg_61 ?_dcg_63) !
 (unify ?_dcg_63 ?_dcg_62))
(<- (filter_vars ?n ?goal ?_dcg_64 ?_dcg_65) (> ?n 0) (unify ?_dcg_64 ?_dcg_66) !
 (unify ?_dcg_66 ?_dcg_67) (arg ?n ?goal ?v) (unify ?_dcg_67 ?_dcg_68)
 (filter_vars_arg ?n ?goal ?v ?_dcg_68 ?_dcg_65))
(<- (filter_vars_arg ?n ?goal ?v ?_dcg_69 ?_dcg_70) (var ?v) (unify ?_dcg_69 ?_dcg_71) !
 (unify ?_dcg_71 ?_dcg_72) (unify ?_dcg_72 (?v . ?_dcg_73)) (is ?n1 (- ?n 1))
 (unify ?_dcg_73 ?_dcg_74) (filter_vars ?n1 ?goal ?_dcg_74 ?_dcg_70))
(<- (filter_vars_arg ?n ?goal ?v ?_dcg_75 ?_dcg_76) (nonvar ?v) (unify ?_dcg_75 ?_dcg_77) !
 (unify ?_dcg_77 ?_dcg_78) (is ?n1 (- ?n 1)) (unify ?_dcg_78 ?_dcg_79)
 (filter_vars ?n1 ?goal ?_dcg_79 ?_dcg_76))
(<- (goal_dupset ?goal ?dupset) (goal_dupset_varbag ?goal ?dupset _))
(<- (goal_dupset_varset ?goal ?dupset ?varset) (goal_dupset_varbag ?goal ?dupset ?varbag)
 (sort ?varbag ?varset))
(<- (goal_dupset_varbag ?goal ?dupset ?varbag) (varbag ?goal ?varbag) (make_key ?varbag ?keybag)
 (keysort ?keybag ?keyset) (filter_dups ?keyset ?dupset))
(<- (make_key nil nil))
(<- (make_key (?v . ?bag) ((- ?v dummy) . ?keybag)) (make_key ?bag ?keybag))
(<- (filter_dups ?keyset ?set) (filter_dups ?keyset ?set nil))
(<- (filter_dups nil ?_dcg_80 ?_dcg_81) ! (unify ?_dcg_80 ?_dcg_81))
(<- (filter_dups ((- ?v1 _) (- ?v2 _) (- ?v3 _) . ?keyset) ?_dcg_82 ?_dcg_83) (== ?v1 ?v2)
 (== ?v2 ?v3) (unify ?_dcg_82 ?_dcg_84) ! (unify ?_dcg_84 ?_dcg_85)
 (filter_dups ((- ?v2 _) (- ?v3 _) . ?keyset) ?_dcg_85 ?_dcg_83))
(<- (filter_dups ((- ?v1 _) (- ?v2 _) . ?keyset) ?_dcg_86 ?_dcg_87) (== ?v1 ?v2)
 (unify ?_dcg_86 ?_dcg_88) ! (unify ?_dcg_88 ?_dcg_89) (unify ?_dcg_89 (?v1 . ?_dcg_90))
 (filter_dups ?keyset ?_dcg_90 ?_dcg_87))
(<- (filter_dups ((- ?v1 _) . ?keyset) ?_dcg_91 ?_dcg_92) ! (unify ?_dcg_91 ?_dcg_93)
 (filter_dups ?keyset ?_dcg_93 ?_dcg_92))
(<- (set_command (sub ?x) ?in ?out) (diffv ?in (?x) ?out))
(<- (set_command (add ?x) ?in ?out) (includev ?x ?in ?out))
(<- (set_command (sub_set ?x) ?in ?out) (diffv ?in ?x ?out))
(<- (set_command (add_set ?x) ?in ?out) (unionv ?x ?in ?out))
(<- (table_command (get ?i ?val) ?in ?in) (get ?in ?i ?val))
(<- (table_command (set ?i ?val) ?in ?out) (set ?in ?i ?val ?out))
(<- (inv ?a (?b . ?s)) (compare ?order ?a ?b) (inv_2 ?order ?a ?s))
(<- (inv_2 = _ _))
(<- (inv_2 > ?a ?s) (inv ?a ?s))
(<- (intersectv nil _ nil))
(<- (intersectv (?a . ?s1) ?s2 ?s) (intersectv_2 ?s2 ?a ?s1 ?s))
(<- (intersectv_2 nil ?a ?s1 nil))
(<- (intersectv_2 (?b . ?s2) ?a ?s1 ?s) (compare ?order ?a ?b)
 (intersectv_3 ?order ?a ?s1 ?b ?s2 ?s))
(<- (intersectv_3 < ?a ?s1 ?b ?s2 ?s) (intersectv_2 ?s1 ?b ?s2 ?s))
(<- (intersectv_3 = ?a ?s1 _ ?s2 (?a . ?s)) (intersectv ?s1 ?s2 ?s))
(<- (intersectv_3 > ?a ?s1 ?b ?s2 ?s) (intersectv_2 ?s2 ?a ?s1 ?s))
(<- (diffv nil _ nil))
(<- (diffv (?a . ?s1) ?s2 ?s) (diffv_2 ?s2 ?a ?s1 ?s))
(<- (diffv_2 nil ?a ?s1 (?a)))
(<- (diffv_2 (?b . ?s2) ?a ?s1 ?s) (compare ?order ?a ?b) (diffv_3 ?order ?a ?s1 ?b ?s2 ?s))
(<- (diffv_3 < ?a ?s1 ?b ?s2 (?a . ?s)) (diffv ?s1 (?b . ?s2) ?s))
(<- (diffv_3 = ?a ?s1 _ ?s2 ?s) (diffv ?s1 ?s2 ?s))
(<- (diffv_3 > ?a ?s1 _ ?s2 ?s) (diffv_2 ?s2 ?a ?s1 ?s))
(<- (unionv nil ?s2 ?s2))
(<- (unionv (?a . ?s1) ?s2 ?s) (unionv_2 ?s2 ?a ?s1 ?s))
(<- (unionv_2 nil ?a ?s1 (?a . ?s1)))
(<- (unionv_2 (?b . ?s2) ?a ?s1 ?s) (compare ?order ?a ?b) (unionv_3 ?order ?a ?s1 ?b ?s2 ?s))
(<- (unionv_3 < ?a ?s1 ?b ?s2 (?a . ?s)) (unionv_2 ?s1 ?b ?s2 ?s))
(<- (unionv_3 = ?a ?s1 _ ?s2 (?a . ?s)) (unionv ?s1 ?s2 ?s))
(<- (unionv_3 > ?a ?s1 ?b ?s2 (?b . ?s)) (unionv_2 ?s2 ?a ?s1 ?s))
(<- (includev ?a ?s1 ?s) (includev_2 ?s1 ?a ?s))
(<- (includev_2 nil ?a (?a)))
(<- (includev_2 (?b . ?s1) ?a ?s) (compare ?order ?a ?b) (includev_3 ?order ?a ?b ?s1 ?s))
(<- (includev_3 < ?a ?b ?s1 (?a ?b . ?s1)))
(<- (includev_3 = _ ?b ?s1 (?b . ?s1)))
(<- (includev_3 > ?a ?b ?s1 (?b . ?s)) (includev_2 ?s1 ?a ?s))
(<- (subsetv nil _))
(<- (subsetv (?a . ?s1) (?b . ?s2)) (compare ?order ?a ?b) (subsetv_2 ?order ?a ?s1 ?s2))
(<- (subsetv_2 = ?a ?s1 ?s2) (subsetv ?s1 ?s2))
(<- (subsetv_2 > ?a ?s1 ?s2) (subsetv (?a . ?s1) ?s2))
(<- (varset ?term ?varset) (varbag ?term ?vb) (sort ?vb ?varset))
(<- (varbag ?term ?varbag) (varbag ?term ?varbag nil))
(<- (varbag ?var ?_dcg_94 ?_dcg_95) (var ?var) (unify ?_dcg_94 ?_dcg_96) !
 (unify ?_dcg_96 ?_dcg_97) (unify ?_dcg_97 (?var . ?_dcg_95)))
(<- (varbag ?str ?_dcg_98 ?_dcg_99) (nonvar ?str) ! (functor ?str _ ?arity)
 (unify ?_dcg_98 ?_dcg_100) (varbag ?str 1 ?arity ?_dcg_100 ?_dcg_99))
(<- (varbag ?_str ?n ?arity ?_dcg_101 ?_dcg_102) (> ?n ?arity) (unify ?_dcg_101 ?_dcg_103) !
 (unify ?_dcg_103 ?_dcg_102))
(<- (varbag ?str ?n ?arity ?_dcg_104 ?_dcg_105) (<= ?n ?arity) (unify ?_dcg_104 ?_dcg_106) !
 (unify ?_dcg_106 ?_dcg_107) (arg ?n ?str ?arg) (unify ?_dcg_107 ?_dcg_108)
 (varbag ?arg ?_dcg_108 ?_dcg_109) (is ?n1 (+ ?n 1)) (unify ?_dcg_109 ?_dcg_110)
 (varbag ?str ?n1 ?arity ?_dcg_110 ?_dcg_105))
(<- (unify_p (= _ _)))
(<- (call_p ?g) (\\+ (unify_p ?g)))
(<- (split_unify (= ?x ?y) ?x ?y))
(<- (split_unify (= ?y ?x) ?x ?y))
